/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9b16ab56-babb-4e9b-8334-d5e5388b33e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_M1BBamYWR",
    "aws_user_pools_web_client_id": "4v6bd72ema9ijsh3msaa2ea540",
    "oauth": {
        "domain": "us-east-1m1bbamywr.auth.us-east-1.amazoncognito.com",
        "scope": ["email", "openid", "phone"],
        "redirectSignIn": "https://main.d27uvtfjtw8lzw.amplifyapp.com/create-listing",
        "redirectSignOut": "https://main.d27uvtfjtw8lzw.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "ADDRESS",
        "BIRTHDATE",
        "EMAIL",
        "FAMILY_NAME",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
